import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FAST API + NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className={`${inter.className} min-h-full flex flex-col`}>
        <nav className="w-full bg-black text-white backdrop-blur-md p-4 flex justify-between items-center">
          <Link href="/" className="font-bold text-lg">
            Home
          </Link>
          <div className="space-x-4">
            <Link href="/students">
              Students
            </Link>
            <Link href="/products">
              Products
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
